export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const FACE_RECOGNITION_PENDING = 'FACE_RECOGNITION_PENDING';
export const FACE_RECOGNITION_SUCCESS = 'FACE_RECOGNITION_SUCCESS';
export const FACE_RECOGNITION_FAILED = 'FACE_RECOGNITION_FAILED';
export const SIGN_IN_OUT = 'SIGN_IN_OUT';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const LOAD_USER = 'LOAD_USER';
export const UPDATE_ENTRIES = 'UPDATE_ENTRIES';






